[package]
name = "actix-template"
version = "1.0.0"
edition = "2021"
description = "Template for an Actix server app, hosted on Shuttle"
readme = "README.md"
authors = ["Jeffery D. Mitchell", "<sentinel1909@jeff-mitchell.dev"]
repository = "https://github.com/sentinel1909/shuttle-template-actix"
license = 'MIT'
keywords = ["actix, shuttle"]
categories = ["template"]
publish = false

[dependencies]
actix-web = "4.3.1"
shuttle-actix-web = "0.24.0"
shuttle-runtime = "0.24.0"
tokio = "1.32.0"
tracing = "0.1.37"
